#!/usr/bin/env python3
"""Convert a .tflite file into a C byte array (model_data_ts.h) for the firmware."""

import argparse
import os

TEMPLATE = """/* {header} - {src} embedded as a byte array
 * AUTO-GENERATED by ai_timeseries/export_model_header.py - DO NOT edit by hand.
 *
 * Smart IV time-series FORECASTER:
 *   in  : int8[1][1][{window}][{nch}]  = past {window} seconds x {nch} channels (normalised)
 *   out : int8[1][{outlen}]            = forecast, {horizon} seconds x {nch} channels, FLAT
 *                                        (index: out[h * {nch} + c])
 *
 * Only 6 operators, all of them MVP-accelerated on the EFR32xG26:
 *   CONV_2D x3, RESHAPE x1, FULLY_CONNECTED x2
 *
 * Quantisation constants (float <-> int8 conversion, see the runner):
 *   IN_SCALE  = {in_scale}
 *   IN_ZP     = {in_zp}
 *   OUT_SCALE = {out_scale}
 *   OUT_ZP    = {out_zp}
 */
#ifndef {guard}
#define {guard}

#include <stdint.h>

#define TS_WINDOW    {window}
#define TS_HORIZON   {horizon}
#define TS_N_CH      {nch}
#define TS_OUT_LEN   {outlen}

#define TS_IN_SCALE  {in_scale}f
#define TS_IN_ZP     {in_zp}
#define TS_OUT_SCALE {out_scale}f
#define TS_OUT_ZP    {out_zp}

/* 16-byte aligned for TFLM */
const unsigned char g_ts_model_data[] __attribute__((aligned(16))) = {{
{body}}};

const unsigned int g_ts_model_data_len = {length};

#endif /* {guard} */
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tflite", default="out/forecaster_int8.tflite")
    ap.add_argument("--quant", default="out/quant_params.txt")
    ap.add_argument("--out", default="out/model_data_ts.h")
    args = ap.parse_args()

    data = open(args.tflite, "rb").read()
    q = {}
    for line in open(args.quant):
        if "=" in line:
            k, v = line.strip().split("=", 1)
            q[k] = v

    rows = []
    for i in range(0, len(data), 12):
        rows.append("  " + " ".join(f"0x{b:02x}," for b in data[i:i + 12]))
    body = "\n".join(rows) + "\n"

    window = int(float(q["WINDOW"]))
    horizon = int(float(q["HORIZON"]))
    nch = int(float(q["N_CH"]))

    text = TEMPLATE.format(
        header=os.path.basename(args.out),
        src=os.path.basename(args.tflite),
        guard="MODEL_DATA_TS_H",
        window=window, horizon=horizon, nch=nch, outlen=horizon * nch,
        in_scale=q["IN_SCALE"], in_zp=q["IN_ZP"],
        out_scale=q["OUT_SCALE"], out_zp=q["OUT_ZP"],
        body=body, length=len(data))

    with open(args.out, "w") as f:
        f.write(text)

    print(f"Wrote {args.out}  ({len(data)} byte model, "
          f"{len(text)} byte header)")
    print(f"  window={window} horizon={horizon} n_ch={nch} out_len={horizon*nch}")


if __name__ == "__main__":
    main()
