// This file is generated by ZCL Advanced Platform generator. Please don't edit manually.

// The following is brought in by the endianness component, which all
// applications must include
#include "sl_endianness.h"

#ifndef SILABS_AF_ENDPOINT_CONFIG
#define SILABS_AF_ENDPOINT_CONFIG 1

// Default values for the attributes longer than a pointer, in a form of a
// binary blob. All attribute values with size greater than 2 bytes. Excluding 0
// values and externally saved values. Separate block is generated for
// big-endian and little-endian cases.

#define ZCL_GENERATED_DEFAULTS_COUNT (4)

#if BIGENDIAN_CPU
#define ZCL_GENERATED_DEFAULTS { \
  0x04, 'I', 'C', 'T', 'U', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, /* 0,DEFAULT value for cluster: Basic, attribute: manufacturer name, side: server */ \
  0x0E, 'S', 'm', 'a', 'r', 't', 'I', 'V', '-', 'S', 'e', 'n', 's', 'o', 'r', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, /* 33,DEFAULT value for cluster: Basic, attribute: model identifier, side: server */ \
  0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, /* 66,DEFAULT value for cluster: Over the Air Bootloading, attribute: OTA Upgrade Server ID, side: client */ \
  0xFF, 0xFF, 0xFF, 0xFF, /* 74,DEFAULT value for cluster: Over the Air Bootloading, attribute: Offset (address) into the file, side: client */ \
}
#else //!BIGENDIAN_CPU
#define ZCL_GENERATED_DEFAULTS { \
  0x04, 'I', 'C', 'T', 'U', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, /* 0,DEFAULT value for cluster: Basic, attribute: manufacturer name, side: server */ \
  0x0E, 'S', 'm', 'a', 'r', 't', 'I', 'V', '-', 'S', 'e', 'n', 's', 'o', 'r', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, /* 33,DEFAULT value for cluster: Basic, attribute: model identifier, side: server */ \
  0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, /* 66,DEFAULT value for cluster: Over the Air Bootloading, attribute: OTA Upgrade Server ID, side: client */ \
  0xFF, 0xFF, 0xFF, 0xFF, /* 74,DEFAULT value for cluster: Over the Air Bootloading, attribute: Offset (address) into the file, side: client */ \
}
#endif


// This is an array of sl_zigbee_af_attribute_min_max_value_t structures.

#define ZCL_GENERATED_MIN_MAX_DEFAULT_COUNT (0)
	#define ZCL_GENERATED_MIN_MAX_DEFAULTS { { { .ptrToDefaultValue = (uint8_t*)0x00 }, { .ptrToDefaultValue = (uint8_t*)0x00 }, { .ptrToDefaultValue = (uint8_t*)0x00 } } }


#define ZCL_GENERATED_ATTRIBUTE_COUNT (31)

// This is an array of sl_zigbee_af_attribute_metadata_t structures.
#define ZCL_GENERATED_ATTRIBUTES { \
  { 0x0000, ZCL_INT8U_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_SINGLETON), { (uint8_t*)0x08  } }, /* 0 Cluster: Basic, Attribute: ZCL version, Side: server*/ \
		  { 0x0004, ZCL_CHAR_STRING_ATTRIBUTE_TYPE, 33, (ATTRIBUTE_MASK_SINGLETON), { (uint8_t*)&(generatedDefaults[0]) } }, /* 1 Cluster: Basic, Attribute: manufacturer name, Side: server*/ \
	  { 0x0005, ZCL_CHAR_STRING_ATTRIBUTE_TYPE, 33, (ATTRIBUTE_MASK_SINGLETON), { (uint8_t*)&(generatedDefaults[33]) } }, /* 2 Cluster: Basic, Attribute: model identifier, Side: server*/ \
	  { 0x0007, ZCL_ENUM8_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_SINGLETON), { (uint8_t*)0x00  } }, /* 3 Cluster: Basic, Attribute: power source, Side: server*/ \
		  { 0xFFFD, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_SINGLETON), { (uint8_t*)3  } }, /* 4 Cluster: Basic, Attribute: cluster revision, Side: server*/ \
		  { 0x0000, ZCL_IEEE_ADDRESS_ATTRIBUTE_TYPE, 8, (ATTRIBUTE_MASK_CLIENT), { (uint8_t*)&(generatedDefaults[66]) } }, /* 5 Cluster: Over the Air Bootloading, Attribute: OTA Upgrade Server ID, Side: client*/ \
	  { 0x0001, ZCL_INT32U_ATTRIBUTE_TYPE, 4, (ATTRIBUTE_MASK_CLIENT), { (uint8_t*)&(generatedDefaults[74]) } }, /* 6 Cluster: Over the Air Bootloading, Attribute: Offset (address) into the file, Side: client*/ \
	  { 0x0006, ZCL_ENUM8_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_CLIENT), { (uint8_t*)0x00  } }, /* 7 Cluster: Over the Air Bootloading, Attribute: OTA Upgrade Status, Side: client*/ \
		  { 0xFFFD, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_CLIENT), { (uint8_t*)4  } }, /* 8 Cluster: Over the Air Bootloading, Attribute: cluster revision, Side: client*/ \
		  { 0x0000, ZCL_INT16S_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x0000  } }, /* 9 Cluster: Smart IV Vitals, Attribute: HeartRate, Side: server*/ \
		  { 0x0001, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x0000  } }, /* 10 Cluster: Smart IV Vitals, Attribute: Spo2, Side: server*/ \
		  { 0x0002, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x0000  } }, /* 11 Cluster: Smart IV Vitals, Attribute: FlowRatio, Side: server*/ \
		  { 0x0003, ZCL_INT16S_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x0000  } }, /* 12 Cluster: Smart IV Vitals, Attribute: DropRatio, Side: server*/ \
		  { 0x0004, ZCL_BITMAP16_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x0000  } }, /* 13 Cluster: Smart IV Vitals, Attribute: AlarmBitmap, Side: server*/ \
		  { 0x0005, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x0000  } }, /* 14 Cluster: Smart IV Vitals, Attribute: WeightG, Side: server*/ \
		  { 0x0006, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x0000  } }, /* 15 Cluster: Smart IV Vitals, Attribute: DropsPerMin, Side: server*/ \
		  { 0x0007, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x0064  } }, /* 16 Cluster: Smart IV Vitals, Attribute: TargetFlowMlH, Side: server*/ \
		  { 0x0008, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x0014  } }, /* 17 Cluster: Smart IV Vitals, Attribute: TargetDropsPerMin, Side: server*/ \
		  { 0x0009, ZCL_INT8U_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x00  } }, /* 18 Cluster: Smart IV Vitals, Attribute: TareCommand, Side: server*/ \
		  { 0x000A, ZCL_INT8U_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x00  } }, /* 19 Cluster: Smart IV Vitals, Attribute: HrRecalibrateCommand, Side: server*/ \
		  { 0x000B, ZCL_INT8U_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x00  } }, /* 20 Cluster: Smart IV Vitals, Attribute: HrBaselineSecondsRemaining, Side: server*/ \
		  { 0x000C, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x0000  } }, /* 21 Cluster: Smart IV Vitals, Attribute: HrBaselineBpm, Side: server*/ \
		  { 0x000D, ZCL_INT8U_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x00  } }, /* 22 Cluster: Smart IV Vitals, Attribute: TareEventCount, Side: server*/ \
		  { 0x000E, ZCL_INT8U_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x00  } }, /* 23 Cluster: Smart IV Vitals, Attribute: HrBaselineEventCount, Side: server*/ \
		  { 0x000F, ZCL_BITMAP16_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x0000  } }, /* 24 Cluster: Smart IV Vitals, Attribute: TsFlags, Side: server*/ \
		  { 0x0010, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0xFFFF  } }, /* 25 Cluster: Smart IV Vitals, Attribute: HrForecast16s, Side: server*/ \
		  { 0x0011, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0xFFFF  } }, /* 26 Cluster: Smart IV Vitals, Attribute: Spo2Forecast16s, Side: server*/ \
		  { 0x0012, ZCL_INT16S_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x0000  } }, /* 27 Cluster: Smart IV Vitals, Attribute: HrTrendBpmPerMin, Side: server*/ \
		  { 0x0013, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x0000  } }, /* 28 Cluster: Smart IV Vitals, Attribute: TsAnomalyScoreX100, Side: server*/ \
		  { 0x0014, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0xFFFF  } }, /* 29 Cluster: Smart IV Vitals, Attribute: DropsForecast16s, Side: server*/ \
		  { 0x0015, ZCL_INT16S_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE| ATTRIBUTE_MASK_MANUFACTURER_SPECIFIC), { (uint8_t*)0x0000  } } /* 30 Cluster: Smart IV Vitals, Attribute: DropsTrendDpmPerMin, Side: server*/ \
		 }

 

#define ZCL_GENERATED_CLUSTER_COUNT (3)
	
// This is an array of sl_zigbee_af_cluster_t structures.
#define ZCL_GENERATED_CLUSTERS { \
  { 0x0000, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[0]), 5, 0, CLUSTER_MASK_SERVER, NULL }, /* 0, Endpoint Id: 1, Cluster: Basic, Side: server*/ \
	  { 0x0019, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[5]), 4, 15, CLUSTER_MASK_CLIENT, NULL }, /* 1, Endpoint Id: 1, Cluster: Over the Air Bootloading, Side: client*/ \
	  { 0xFC01, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[9]), 22, 39, CLUSTER_MASK_SERVER, NULL } /* 2, Endpoint Id: 2, Cluster: Smart IV Vitals, Side: server*/ \
	 }

 
#define ZCL_GENERATED_ENDPOINT_TYPE_COUNT (2)

// This is an array of sl_zigbee_af_endpoint_type_t structures.
#define ZCL_GENERATED_ENDPOINT_TYPES { \
  { ((sl_zigbee_af_cluster_t*)&(generatedClusters[0])), 2, 15 }, \
	  { ((sl_zigbee_af_cluster_t*)&(generatedClusters[2])), 1, 39 }, \
	 } 
// Largest attribute size is needed for various buffers
#define ZCL_ATTRIBUTE_LARGEST (33)

// Total size of singleton attributes
#define ZCL_ATTRIBUTE_SINGLETONS_SIZE (70)

// Total size of attribute storage
#define ZCL_ATTRIBUTE_MAX_SIZE (54)

// Number of fixed endpoints	
#define ZCL_FIXED_ENDPOINT_COUNT (2)

// Array of endpoints that are supported, the data inside the array is the
// endpoint number.
#define ZCL_FIXED_ENDPOINT_ARRAY { \
  1, \
  2 \
}

// Array of profile ids
#define ZCL_FIXED_PROFILE_IDS { \
  260, \
  260 \
}

// Array of device ids
#define ZCL_FIXED_DEVICE_IDS { \
  65535, \
  65535 \
}

// Array of device versions
#define ZCL_FIXED_DEVICE_VERSIONS { \
  1, \
  1 \
}

// Array of endpoint types supported on each endpoint
#define ZCL_FIXED_ENDPOINT_TYPES { \
  0, \
  1 \
}

// Array of networks supported on each endpoint
#define ZCL_FIXED_NETWORKS { \
  0, \
  0 \
}

// Array of sl_zigbee_af_command_metadata_t structs.
#define ZCL_ZAP_COMMAND_MASK(mask) COMMAND_MASK_ ## mask
#define SL_ZIGBEE_ZCL_GENERATED_COMMAND_COUNT  (7)
#define ZCL_GENERATED_COMMANDS { \
  { 0x0019, 0x00, COMMAND_MASK_INCOMING_CLIENT }, /* 0, Cluster: Over the Air Bootloading, Command: ImageNotify*/ \
	  { 0x0019, 0x01, COMMAND_MASK_OUTGOING_CLIENT }, /* 1, Cluster: Over the Air Bootloading, Command: QueryNextImageRequest*/ \
	  { 0x0019, 0x02, COMMAND_MASK_INCOMING_CLIENT }, /* 2, Cluster: Over the Air Bootloading, Command: QueryNextImageResponse*/ \
	  { 0x0019, 0x03, COMMAND_MASK_OUTGOING_CLIENT }, /* 3, Cluster: Over the Air Bootloading, Command: ImageBlockRequest*/ \
	  { 0x0019, 0x05, COMMAND_MASK_INCOMING_CLIENT }, /* 4, Cluster: Over the Air Bootloading, Command: ImageBlockResponse*/ \
	  { 0x0019, 0x06, COMMAND_MASK_OUTGOING_CLIENT }, /* 5, Cluster: Over the Air Bootloading, Command: UpgradeEndRequest*/ \
	  { 0x0019, 0x07, COMMAND_MASK_INCOMING_CLIENT }, /* 6, Cluster: Over the Air Bootloading, Command: UpgradeEndResponse*/ \
	 } 
// Array of sl_zigbee_af_manufacturer_code_entry_t structures for commands.
#define ZCL_GENERATED_COMMAND_MANUFACTURER_CODE_COUNT (0)
#define ZCL_GENERATED_COMMAND_MANUFACTURER_CODES { \
  { 0x00, 0x00 }  \
							 } 
// This is an array of sl_zigbee_af_manufacturer_code_entry_t structures for clusters.
#define ZCL_GENERATED_CLUSTER_MANUFACTURER_CODE_COUNT (1)
#define ZCL_GENERATED_CLUSTER_MANUFACTURER_CODES { \
		  { 2, 0x1049 },  \
	 } 
// This is an array of sl_zigbee_af_manufacturer_code_entry_t structures for attributes.
#define ZCL_GENERATED_ATTRIBUTE_MANUFACTURER_CODE_COUNT (22)
#define ZCL_GENERATED_ATTRIBUTE_MANUFACTURER_CODES { \
									  { 9, 0x1049 },  \
	  { 10, 0x1049 },  \
	  { 11, 0x1049 },  \
	  { 12, 0x1049 },  \
	  { 13, 0x1049 },  \
	  { 14, 0x1049 },  \
	  { 15, 0x1049 },  \
	  { 16, 0x1049 },  \
	  { 17, 0x1049 },  \
	  { 18, 0x1049 },  \
	  { 19, 0x1049 },  \
	  { 20, 0x1049 },  \
	  { 21, 0x1049 },  \
	  { 22, 0x1049 },  \
	  { 23, 0x1049 },  \
	  { 24, 0x1049 },  \
	  { 25, 0x1049 },  \
	  { 26, 0x1049 },  \
	  { 27, 0x1049 },  \
	  { 28, 0x1049 },  \
	  { 29, 0x1049 },  \
	  { 30, 0x1049 },  \
	 } 
// Array of sl_zigbee_af_plugin_reporting_entry_t structures.
#define SL_ZIGBEE_ZCL_GENERATED_REPORTING_CONFIG_DEFAULTS_TABLE_SIZE (20)
#define SL_ZIGBEE_ZCL_GENERATED_REPORTING_CONFIG_DEFAULTS { \
  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x0000, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: HeartRate */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x0001, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: Spo2 */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x0002, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: FlowRatio */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x0003, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: DropRatio */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x0004, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: AlarmBitmap */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x0005, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: WeightG */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x0006, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: DropsPerMin */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x0007, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: TargetFlowMlH */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x0008, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: TargetDropsPerMin */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x000B, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: HrBaselineSecondsRemaining */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x000C, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: HrBaselineBpm */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x000D, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: TareEventCount */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x000E, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: HrBaselineEventCount */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x000F, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: TsFlags */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x0010, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: HrForecast16s */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x0011, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: Spo2Forecast16s */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x0012, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: HrTrendBpmPerMin */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x0013, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: TsAnomalyScoreX100 */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x0014, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: DropsForecast16s */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0002, 0xFC01, 0x0015, CLUSTER_MASK_SERVER, 0x1049, .data.reported={ 1, 60, 0 } }, /* Endpoint Id: 2, Cluster: Smart IV Vitals, Attribute: DropsTrendDpmPerMin */ \
	 } 

#define SL_ZIGBEE_ZCL_MANUFACTURER_CODE 0x1049
#define SL_ZIGBEE_AF_DEFAULT_RESPONSE_POLICY_ALWAYS

// All Enabled Clusters
#define ZCL_USING_BASIC_CLUSTER_SERVER
#define ZCL_USING_OTA_BOOTLOAD_CLUSTER_CLIENT
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_SERVER

// Cluster Counts
#define SL_ZIGBEE_ZCL_BASIC_CLUSTER_SERVER_ENDPOINT_COUNT (1)
#define SL_ZIGBEE_ZCL_OTA_BOOTLOAD_CLUSTER_CLIENT_ENDPOINT_COUNT (1)
#define SL_ZIGBEE_ZCL_SMART_IV_VITALS_CLUSTER_SERVER_ENDPOINT_COUNT (1)

// All Enabled Cluster Attributes
#define ZCL_USING_BASIC_CLUSTER_VERSION_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_MANUFACTURER_NAME_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_MODEL_IDENTIFIER_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_POWER_SOURCE_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_CLUSTER_REVISION_SERVER_ATTRIBUTE
#define ZCL_USING_OTA_BOOTLOAD_CLUSTER_UPGRADE_SERVER_ID_ATTRIBUTE
#define ZCL_USING_OTA_BOOTLOAD_CLUSTER_FILE_OFFSET_ATTRIBUTE
#define ZCL_USING_OTA_BOOTLOAD_CLUSTER_IMAGE_UPGRADE_STATUS_ATTRIBUTE
#define ZCL_USING_OTA_BOOTLOAD_CLUSTER_CLUSTER_REVISION_CLIENT_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_HEART_RATE_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_SPO2_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_FLOW_RATIO_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_DROP_RATIO_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_ALARM_BITMAP_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_WEIGHT_G_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_DROPS_PER_MIN_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_TARGET_FLOW_ML_H_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_TARGET_DROPS_PER_MIN_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_TARE_COMMAND_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_HR_RECALIBRATE_COMMAND_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_HR_BASELINE_SECONDS_REMAINING_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_HR_BASELINE_BPM_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_TARE_EVENT_COUNT_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_HR_BASELINE_EVENT_COUNT_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_TS_FLAGS_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_HR_FORECAST_16_S_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_SPO2_FORECAST_16_S_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_HR_TREND_BPM_PER_MIN_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_TS_ANOMALY_SCORE_X100_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_DROPS_FORECAST_16_S_ATTRIBUTE
#define ZCL_USING_SMART_IV_VITALS_CLUSTER_DROPS_TREND_DPM_PER_MIN_ATTRIBUTE

#define SL_ZIGBEE_AF_SUPPORT_COMMAND_DISCOVERY

/* Format: Zigbee Cluster Code, Zigbee Cluster Mfg Code, Matter Cluster Code, Matter Cluster Mfg Code, Zigbee Attribute Code, Zigbee Attribute Mfg Code, Zigbee Attribute Type Identifier, Matter Attribute Code, Matter Attribute Mfg Code, Matter Attribute Type Identifier */
#define GENERATED_MULTI_PROTOCOL_ATTRIBUTE_MAPPING \
{ \
  { 0x0000, 0x0000, 16, 0x0000, 0x0000, 16 }, /* 0, Zigbee Cluster: On/off, Matter Cluster: On/Off, Zigbee Attribute: on/off, Matter Attribute: OnOff */ \
  { 0x4003, 0x0000, 48, 0x4003, 0x0000, 48 }, /* 1, Zigbee Cluster: On/off, Matter Cluster: On/Off, Zigbee Attribute: start up on off, Matter Attribute: StartUpOnOff */ \
  { 0x0000, 0x0000, 32, 0x0000, 0x0000, 32 }, /* 2, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: current level, Matter Attribute: CurrentLevel */ \
  { 0x0001, 0x0000, 33, 0x0001, 0x0000, 33 }, /* 3, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: remaining time, Matter Attribute: RemainingTime */ \
  { 0x0002, 0x0000, 32, 0x0002, 0x0000, 32 }, /* 4, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: min level, Matter Attribute: MinLevel */ \
  { 0x0003, 0x0000, 32, 0x0003, 0x0000, 32 }, /* 5, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: max level, Matter Attribute: MaxLevel */ \
  { 0x0004, 0x0000, 33, 0x0004, 0x0000, 33 }, /* 6, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: current frequency, Matter Attribute: CurrentFrequency */ \
  { 0x0005, 0x0000, 33, 0x0005, 0x0000, 33 }, /* 7, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: min frequency, Matter Attribute: MinFrequency */ \
  { 0x0006, 0x0000, 33, 0x0006, 0x0000, 33 }, /* 8, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: max frequency, Matter Attribute: MaxFrequency */ \
  { 0x000F, 0x0000, 24, 0x000F, 0x0000, 24 }, /* 9, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: options, Matter Attribute: Options */ \
  { 0x0010, 0x0000, 33, 0x0010, 0x0000, 33 }, /* 10, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: on off transition time, Matter Attribute: OnOffTransitionTime */ \
  { 0x0011, 0x0000, 32, 0x0011, 0x0000, 32 }, /* 11, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: on level, Matter Attribute: OnLevel */ \
  { 0x0012, 0x0000, 33, 0x0012, 0x0000, 33 }, /* 12, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: on transition time, Matter Attribute: OnTransitionTime */ \
  { 0x0013, 0x0000, 33, 0x0013, 0x0000, 33 }, /* 13, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: off transition time, Matter Attribute: OffTransitionTime */ \
  { 0x0014, 0x0000, 32, 0x0014, 0x0000, 32 }, /* 14, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: default move rate, Matter Attribute: DefaultMoveRate */ \
  { 0x4000, 0x0000, 32, 0x4000, 0x0000, 32 }, /* 15, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: start up current level, Matter Attribute: StartUpCurrentLevel */ \
  { 0x0000, 0x0000, 41, 0x0000, 0x0000, 216 }, /* 16, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: local temperature, Matter Attribute: LocalTemperature */ \
  { 0x0001, 0x0000, 41, 0x0001, 0x0000, 216 }, /* 17, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: outdoor temperature, Matter Attribute: OutdoorTemperature */ \
  { 0x0002, 0x0000, 24, 0x0002, 0x0000, 24 }, /* 18, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: occupancy, Matter Attribute: Occupancy */ \
  { 0x0003, 0x0000, 41, 0x0003, 0x0000, 216 }, /* 19, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: abs min heat setpoint limit, Matter Attribute: AbsMinHeatSetpointLimit */ \
  { 0x0004, 0x0000, 41, 0x0004, 0x0000, 216 }, /* 20, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: abs max heat setpoint limit, Matter Attribute: AbsMaxHeatSetpointLimit */ \
  { 0x0005, 0x0000, 41, 0x0005, 0x0000, 216 }, /* 21, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: abs min cool setpoint limit, Matter Attribute: AbsMinCoolSetpointLimit */ \
  { 0x0006, 0x0000, 41, 0x0006, 0x0000, 216 }, /* 22, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: abs max cool setpoint limit, Matter Attribute: AbsMaxCoolSetpointLimit */ \
  { 0x0007, 0x0000, 32, 0x0007, 0x0000, 32 }, /* 23, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: pi cooling demand, Matter Attribute: PICoolingDemand */ \
  { 0x0008, 0x0000, 32, 0x0008, 0x0000, 32 }, /* 24, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: pi heating demand, Matter Attribute: PIHeatingDemand */ \
  { 0x0009, 0x0000, 24, 0x0009, 0x0000, 24 }, /* 25, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: HVAC system type configuration, Matter Attribute: HVACSystemTypeConfiguration */ \
  { 0x0010, 0x0000, 40, 0x0010, 0x0000, 40 }, /* 26, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: local temperature calibration, Matter Attribute: LocalTemperatureCalibration */ \
  { 0x0011, 0x0000, 41, 0x0011, 0x0000, 216 }, /* 27, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: occupied cooling setpoint, Matter Attribute: OccupiedCoolingSetpoint */ \
  { 0x0012, 0x0000, 41, 0x0012, 0x0000, 216 }, /* 28, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: occupied heating setpoint, Matter Attribute: OccupiedHeatingSetpoint */ \
  { 0x0013, 0x0000, 41, 0x0013, 0x0000, 216 }, /* 29, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: unoccupied cooling setpoint, Matter Attribute: UnoccupiedCoolingSetpoint */ \
  { 0x0014, 0x0000, 41, 0x0014, 0x0000, 216 }, /* 30, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: unoccupied heating setpoint, Matter Attribute: UnoccupiedHeatingSetpoint */ \
  { 0x0015, 0x0000, 41, 0x0015, 0x0000, 216 }, /* 31, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: min heat setpoint limit, Matter Attribute: MinHeatSetpointLimit */ \
  { 0x0016, 0x0000, 41, 0x0016, 0x0000, 216 }, /* 32, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: max heat setpoint limit, Matter Attribute: MaxHeatSetpointLimit */ \
  { 0x0017, 0x0000, 41, 0x0017, 0x0000, 216 }, /* 33, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: min cool setpoint limit, Matter Attribute: MinCoolSetpointLimit */ \
  { 0x0018, 0x0000, 41, 0x0018, 0x0000, 216 }, /* 34, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: max cool setpoint limit, Matter Attribute: MaxCoolSetpointLimit */ \
  { 0x0019, 0x0000, 40, 0x0019, 0x0000, 40 }, /* 35, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: min setpoint dead band, Matter Attribute: MinSetpointDeadBand */ \
  { 0x001A, 0x0000, 24, 0x001A, 0x0000, 24 }, /* 36, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: remote sensing, Matter Attribute: RemoteSensing */ \
  { 0x001B, 0x0000, 48, 0x001B, 0x0000, 48 }, /* 37, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: control sequence of operation, Matter Attribute: ControlSequenceOfOperation */ \
  { 0x001C, 0x0000, 48, 0x001C, 0x0000, 48 }, /* 38, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: system mode, Matter Attribute: SystemMode */ \
  { 0x001E, 0x0000, 48, 0x001E, 0x0000, 48 }, /* 39, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: thermostat running mode, Matter Attribute: ThermostatRunningMode */ \
  { 0x0020, 0x0000, 48, 0x0020, 0x0000, 48 }, /* 40, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: start of week, Matter Attribute: StartOfWeek */ \
  { 0x0021, 0x0000, 32, 0x0021, 0x0000, 32 }, /* 41, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: number of weekly transitions, Matter Attribute: NumberOfWeeklyTransitions */ \
  { 0x0022, 0x0000, 32, 0x0022, 0x0000, 32 }, /* 42, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: number of daily transitions, Matter Attribute: NumberOfDailyTransitions */ \
  { 0x0023, 0x0000, 48, 0x0023, 0x0000, 48 }, /* 43, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: temperature setpoint hold, Matter Attribute: TemperatureSetpointHold */ \
  { 0x0024, 0x0000, 33, 0x0024, 0x0000, 33 }, /* 44, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: temperature setpoint hold duration, Matter Attribute: TemperatureSetpointHoldDuration */ \
  { 0x0025, 0x0000, 24, 0x0025, 0x0000, 24 }, /* 45, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: thermostat programming operation mode, Matter Attribute: ThermostatProgrammingOperationMode */ \
  { 0x0029, 0x0000, 25, 0x0029, 0x0000, 25 }, /* 46, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: hvac relay state, Matter Attribute: ThermostatRunningState */ \
  { 0x0030, 0x0000, 48, 0x0030, 0x0000, 48 }, /* 47, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: setpoint change source, Matter Attribute: SetpointChangeSource */ \
  { 0x0031, 0x0000, 41, 0x0031, 0x0000, 41 }, /* 48, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: setpoint change amount, Matter Attribute: SetpointChangeAmount */ \
  { 0x0032, 0x0000, 226, 0x0032, 0x0000, 228 }, /* 49, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: setpoint change source timestamp, Matter Attribute: SetpointChangeSourceTimestamp */ \
  { 0x0034, 0x0000, 32, 0x0034, 0x0000, 32 }, /* 50, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: occupied setback, Matter Attribute: OccupiedSetback */ \
  { 0x0035, 0x0000, 32, 0x0035, 0x0000, 32 }, /* 51, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: occupied setback min, Matter Attribute: OccupiedSetbackMin */ \
  { 0x0036, 0x0000, 32, 0x0036, 0x0000, 32 }, /* 52, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: occupied setback max, Matter Attribute: OccupiedSetbackMax */ \
  { 0x0037, 0x0000, 32, 0x0037, 0x0000, 32 }, /* 53, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: unoccupied setback, Matter Attribute: UnoccupiedSetback */ \
  { 0x0038, 0x0000, 32, 0x0038, 0x0000, 32 }, /* 54, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: unoccupied setback min, Matter Attribute: UnoccupiedSetbackMin */ \
  { 0x0039, 0x0000, 32, 0x0039, 0x0000, 32 }, /* 55, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: unoccupied setback max, Matter Attribute: UnoccupiedSetbackMax */ \
  { 0x003A, 0x0000, 32, 0x003A, 0x0000, 32 }, /* 56, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: emergency heat delta, Matter Attribute: EmergencyHeatDelta */ \
  { 0x0040, 0x0000, 48, 0x0040, 0x0000, 48 }, /* 57, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: ac type, Matter Attribute: ACType */ \
  { 0x0041, 0x0000, 33, 0x0041, 0x0000, 33 }, /* 58, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: ac capacity, Matter Attribute: ACCapacity */ \
  { 0x0042, 0x0000, 48, 0x0042, 0x0000, 48 }, /* 59, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: ac refrigerant type, Matter Attribute: ACRefrigerantType */ \
  { 0x0043, 0x0000, 48, 0x0043, 0x0000, 48 }, /* 60, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: ac compressor, Matter Attribute: ACCompressorType */ \
  { 0x0044, 0x0000, 27, 0x0044, 0x0000, 27 }, /* 61, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: ac error code, Matter Attribute: ACErrorCode */ \
  { 0x0045, 0x0000, 48, 0x0045, 0x0000, 48 }, /* 62, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: ac louver position, Matter Attribute: ACLouverPosition */ \
  { 0x0046, 0x0000, 41, 0x0046, 0x0000, 216 }, /* 63, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: ac coil temperature, Matter Attribute: ACCoilTemperature */ \
  { 0x0047, 0x0000, 48, 0x0047, 0x0000, 48 }, /* 64, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: ac capacity format, Matter Attribute: ACCapacityformat */ \
  { 0x0000, 0x0000, 48, 0x0000, 0x0000, 48 }, /* 65, Zigbee Cluster: Thermostat User Interface Configuration, Matter Cluster: Thermostat User Interface Configuration, Zigbee Attribute: temperature display mode, Matter Attribute: TemperatureDisplayMode */ \
  { 0x0001, 0x0000, 48, 0x0001, 0x0000, 48 }, /* 66, Zigbee Cluster: Thermostat User Interface Configuration, Matter Cluster: Thermostat User Interface Configuration, Zigbee Attribute: keypad lockout, Matter Attribute: KeypadLockout */ \
  { 0x0002, 0x0000, 48, 0x0002, 0x0000, 48 }, /* 67, Zigbee Cluster: Thermostat User Interface Configuration, Matter Cluster: Thermostat User Interface Configuration, Zigbee Attribute: schedule programming visibility, Matter Attribute: ScheduleProgrammingVisibility */ \
  { 0x0000, 0x0000, 32, 0x0000, 0x0000, 32 }, /* 68, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: current hue, Matter Attribute: CurrentHue */ \
  { 0x0001, 0x0000, 32, 0x0001, 0x0000, 32 }, /* 69, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: current saturation, Matter Attribute: CurrentSaturation */ \
  { 0x0002, 0x0000, 33, 0x0002, 0x0000, 33 }, /* 70, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: remaining time, Matter Attribute: RemainingTime */ \
  { 0x0003, 0x0000, 33, 0x0003, 0x0000, 33 }, /* 71, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: current x, Matter Attribute: CurrentX */ \
  { 0x0004, 0x0000, 33, 0x0004, 0x0000, 33 }, /* 72, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: current y, Matter Attribute: CurrentY */ \
  { 0x0005, 0x0000, 48, 0x0005, 0x0000, 48 }, /* 73, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: drift compensation, Matter Attribute: DriftCompensation */ \
  { 0x0006, 0x0000, 66, 0x0006, 0x0000, 66 }, /* 74, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: compensation text, Matter Attribute: CompensationText */ \
  { 0x0007, 0x0000, 33, 0x0007, 0x0000, 33 }, /* 75, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color temperature, Matter Attribute: ColorTemperatureMireds */ \
  { 0x0008, 0x0000, 48, 0x0008, 0x0000, 48 }, /* 76, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color mode, Matter Attribute: ColorMode */ \
  { 0x000F, 0x0000, 24, 0x000F, 0x0000, 24 }, /* 77, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color control options, Matter Attribute: Options */ \
  { 0x0010, 0x0000, 32, 0x0010, 0x0000, 32 }, /* 78, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: number of primaries, Matter Attribute: NumberOfPrimaries */ \
  { 0x0011, 0x0000, 33, 0x0011, 0x0000, 33 }, /* 79, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 1 x, Matter Attribute: Primary1X */ \
  { 0x0012, 0x0000, 33, 0x0012, 0x0000, 33 }, /* 80, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 1 y, Matter Attribute: Primary1Y */ \
  { 0x0013, 0x0000, 32, 0x0013, 0x0000, 32 }, /* 81, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 1 intensity, Matter Attribute: Primary1Intensity */ \
  { 0x0015, 0x0000, 33, 0x0015, 0x0000, 33 }, /* 82, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 2 x, Matter Attribute: Primary2X */ \
  { 0x0016, 0x0000, 33, 0x0016, 0x0000, 33 }, /* 83, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 2 y, Matter Attribute: Primary2Y */ \
  { 0x0017, 0x0000, 32, 0x0017, 0x0000, 32 }, /* 84, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 2 intensity, Matter Attribute: Primary2Intensity */ \
  { 0x0019, 0x0000, 33, 0x0019, 0x0000, 33 }, /* 85, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 3 x, Matter Attribute: Primary3X */ \
  { 0x001A, 0x0000, 33, 0x001A, 0x0000, 33 }, /* 86, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 3 y, Matter Attribute: Primary3Y */ \
  { 0x001B, 0x0000, 32, 0x001B, 0x0000, 32 }, /* 87, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 3 intensity, Matter Attribute: Primary3Intensity */ \
  { 0x0020, 0x0000, 33, 0x0020, 0x0000, 33 }, /* 88, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 4 x, Matter Attribute: Primary4X */ \
  { 0x0021, 0x0000, 33, 0x0021, 0x0000, 33 }, /* 89, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 4 y, Matter Attribute: Primary4Y */ \
  { 0x0022, 0x0000, 32, 0x0022, 0x0000, 32 }, /* 90, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 4 intensity, Matter Attribute: Primary4Intensity */ \
  { 0x0024, 0x0000, 33, 0x0024, 0x0000, 33 }, /* 91, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 5 x, Matter Attribute: Primary5X */ \
  { 0x0025, 0x0000, 33, 0x0025, 0x0000, 33 }, /* 92, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 5 y, Matter Attribute: Primary5Y */ \
  { 0x0026, 0x0000, 32, 0x0026, 0x0000, 32 }, /* 93, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 5 intensity, Matter Attribute: Primary5Intensity */ \
  { 0x0028, 0x0000, 33, 0x0028, 0x0000, 33 }, /* 94, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 6 x, Matter Attribute: Primary6X */ \
  { 0x0029, 0x0000, 33, 0x0029, 0x0000, 33 }, /* 95, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 6 y, Matter Attribute: Primary6Y */ \
  { 0x002A, 0x0000, 32, 0x002A, 0x0000, 32 }, /* 96, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 6 intensity, Matter Attribute: Primary6Intensity */ \
  { 0x0030, 0x0000, 33, 0x0030, 0x0000, 33 }, /* 97, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: white point x, Matter Attribute: WhitePointX */ \
  { 0x0031, 0x0000, 33, 0x0031, 0x0000, 33 }, /* 98, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: white point y, Matter Attribute: WhitePointY */ \
  { 0x0032, 0x0000, 33, 0x0032, 0x0000, 33 }, /* 99, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color point r x, Matter Attribute: ColorPointRX */ \
  { 0x0033, 0x0000, 33, 0x0033, 0x0000, 33 }, /* 100, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color point r y, Matter Attribute: ColorPointRY */ \
  { 0x0034, 0x0000, 32, 0x0034, 0x0000, 32 }, /* 101, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color point r intensity, Matter Attribute: ColorPointRIntensity */ \
  { 0x0036, 0x0000, 33, 0x0036, 0x0000, 33 }, /* 102, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color point g x, Matter Attribute: ColorPointGX */ \
  { 0x0037, 0x0000, 33, 0x0037, 0x0000, 33 }, /* 103, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color point g y, Matter Attribute: ColorPointGY */ \
  { 0x0038, 0x0000, 32, 0x0038, 0x0000, 32 }, /* 104, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color point g intensity, Matter Attribute: ColorPointGIntensity */ \
  { 0x003A, 0x0000, 33, 0x003A, 0x0000, 33 }, /* 105, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color point b x, Matter Attribute: ColorPointBX */ \
  { 0x003B, 0x0000, 33, 0x003B, 0x0000, 33 }, /* 106, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color point b y, Matter Attribute: ColorPointBY */ \
  { 0x003C, 0x0000, 32, 0x003C, 0x0000, 32 }, /* 107, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color point b intensity, Matter Attribute: ColorPointBIntensity */ \
  { 0x4000, 0x0000, 33, 0x4000, 0x0000, 33 }, /* 108, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: enhanced current hue, Matter Attribute: EnhancedCurrentHue */ \
  { 0x4001, 0x0000, 48, 0x4001, 0x0000, 48 }, /* 109, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: enhanced color mode, Matter Attribute: EnhancedColorMode */ \
  { 0x4002, 0x0000, 32, 0x4002, 0x0000, 32 }, /* 110, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color loop active, Matter Attribute: ColorLoopActive */ \
  { 0x4003, 0x0000, 32, 0x4003, 0x0000, 32 }, /* 111, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color loop direction, Matter Attribute: ColorLoopDirection */ \
  { 0x4004, 0x0000, 33, 0x4004, 0x0000, 33 }, /* 112, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color loop time, Matter Attribute: ColorLoopTime */ \
  { 0x4005, 0x0000, 33, 0x4005, 0x0000, 33 }, /* 113, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color loop start enhanced hue, Matter Attribute: ColorLoopStartEnhancedHue */ \
  { 0x4006, 0x0000, 33, 0x4006, 0x0000, 33 }, /* 114, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color loop stored enhanced hue, Matter Attribute: ColorLoopStoredEnhancedHue */ \
  { 0x400A, 0x0000, 25, 0x400A, 0x0000, 25 }, /* 115, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color capabilities, Matter Attribute: ColorCapabilities */ \
  { 0x400B, 0x0000, 33, 0x400B, 0x0000, 33 }, /* 116, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color temp physical min, Matter Attribute: ColorTempPhysicalMinMireds */ \
  { 0x400C, 0x0000, 33, 0x400C, 0x0000, 33 }, /* 117, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color temp physical max, Matter Attribute: ColorTempPhysicalMaxMireds */ \
  { 0x400D, 0x0000, 33, 0x400D, 0x0000, 33 }, /* 118, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: couple color temp to level min-mireds, Matter Attribute: CoupleColorTempToLevelMinMireds */ \
  { 0x4010, 0x0000, 33, 0x4010, 0x0000, 33 } /* 119, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: start up color temperature mireds, Matter Attribute: StartUpColorTemperatureMireds */ \
}

#define GENERATED_MULTI_PROTOCOL_CLUSTER_MAPPING \
{ \
{ 0x0006, 0x0000, 0x0006, 0x0000, (sl_zigbee_matter_af_multi_protocol_attribute_metadata_t*)&multiProtocolAttributeMap[0], 2 }, /* Zigbee Cluster: On/off, Matter Cluster: On/Off */ \
{ 0x0008, 0x0000, 0x0008, 0x0000, (sl_zigbee_matter_af_multi_protocol_attribute_metadata_t*)&multiProtocolAttributeMap[2], 14 }, /* Zigbee Cluster: Level Control, Matter Cluster: Level Control */ \
{ 0x0201, 0x0000, 0x0201, 0x0000, (sl_zigbee_matter_af_multi_protocol_attribute_metadata_t*)&multiProtocolAttributeMap[16], 49 }, /* Zigbee Cluster: Thermostat, Matter Cluster: Thermostat */ \
{ 0x0204, 0x0000, 0x0204, 0x0000, (sl_zigbee_matter_af_multi_protocol_attribute_metadata_t*)&multiProtocolAttributeMap[65], 3 }, /* Zigbee Cluster: Thermostat User Interface Configuration, Matter Cluster: Thermostat User Interface Configuration */ \
{ 0x0300, 0x0000, 0x0300, 0x0000, (sl_zigbee_matter_af_multi_protocol_attribute_metadata_t*)&multiProtocolAttributeMap[68], 52 } /* Zigbee Cluster: Color Control, Matter Cluster: Color Control */ \
}

#endif // SILABS_AF_ENDPOINT_CONFIG